bot:
  TOKEN: "${TOKEN}"
  OWNER_ID: "${OWNER_ID}"

  AVOID_SUSPEND: true

player:
  NODES:
    - host: "${LAVALINK_HOST}"
      port: ${LAVALINK_PORT}
      name: "main"
      auth: "${LAVALINK_PASSWORD}"
      secure: ${LAVALINK_SECURE}
