bot:
  TOKEN: 'YOUR_BOT_TOKEN'
  OWNER_ID: '1074147049735467058'

player:
  NODES:
    - host: 'lavalink-4.railway.internal'
      port: 8080
      name: 'Lunox'
      auth: 'gkhmusic'
      secure: false
